// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpclient

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCodec creates a new instance of MockCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodec {
	mock := &MockCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodec is an autogenerated mock type for the Codec type
type MockCodec struct {
	mock.Mock
}

type MockCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodec) EXPECT() *MockCodec_Expecter {
	return &MockCodec_Expecter{mock: &_m.Mock}
}

// ContentType provides a mock function for the type MockCodec
func (_mock *MockCodec) ContentType() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCodec_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type MockCodec_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
func (_e *MockCodec_Expecter) ContentType() *MockCodec_ContentType_Call {
	return &MockCodec_ContentType_Call{Call: _e.mock.On("ContentType")}
}

func (_c *MockCodec_ContentType_Call) Run(run func()) *MockCodec_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodec_ContentType_Call) Return(s string) *MockCodec_ContentType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCodec_ContentType_Call) RunAndReturn(run func() string) *MockCodec_ContentType_Call {
	_c.Call.Return(run)
	return _c
}

// Marshal provides a mock function for the type MockCodec
func (_mock *MockCodec) Marshal(v any) ([]byte, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) ([]byte, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(any) []byte); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCodec_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type MockCodec_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - v any
func (_e *MockCodec_Expecter) Marshal(v any) *MockCodec_Marshal_Call {
	return &MockCodec_Marshal_Call{Call: _e.mock.On("Marshal", v)}
}

func (_c *MockCodec_Marshal_Call) Run(run func(v any)) *MockCodec_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodec_Marshal_Call) Return(bytes []byte, err error) *MockCodec_Marshal_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCodec_Marshal_Call) RunAndReturn(run func(v any) ([]byte, error)) *MockCodec_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type MockCodec
func (_mock *MockCodec) Unmarshal(data []byte, v any) error {
	ret := _mock.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, any) error); ok {
		r0 = returnFunc(data, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCodec_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockCodec_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - data []byte
//   - v any
func (_e *MockCodec_Expecter) Unmarshal(data any, v any) *MockCodec_Unmarshal_Call {
	return &MockCodec_Unmarshal_Call{Call: _e.mock.On("Unmarshal", data, v)}
}

func (_c *MockCodec_Unmarshal_Call) Run(run func(data []byte, v any)) *MockCodec_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCodec_Unmarshal_Call) Return(err error) *MockCodec_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCodec_Unmarshal_Call) RunAndReturn(run func(data []byte, v any) error) *MockCodec_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}
